spring.application.name=gigafix-backend

#database setter
#${aaa:bbb}if there is not aaa, the system will use bbb for value
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=giga_fix;encrypt=true;trustServerCertificate=true;}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gigafixer}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Hibernate Setter
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#jwt Secret Key(Base64 Encoded)
jwt.secret=${JWT_SECRET:TW9zdCBzdHVkZW50cyBhcmUgc2xhY2tpbmcgb2ZmIHdoaWxlIGxlYXJuaW5nIHRvIGNvZGUgaW4gVGFveXVhbiBpU3BhbiBFRUlUMjM=}
#jwt expire_time(in seconds)
jwt.expire_time=1800

server.servlet.session.timeout=30m

#Mail Sender Setter
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GIGAFIX_GMAIL_USERNAME}
spring.mail.password=${GIGAFIX_GMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000