spring.application.name=gigafix-backend

#database setter
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=giga_fix;encrypt=true;trustServerCertificate=true;
spring.datasource.username=gigafixer
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Hibernate Setter
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

#jwt Secret Key(Base64 Encoded)
jwt.secret=TW9zdCBzdHVkZW50cyBhcmUgc2xhY2tpbmcgb2ZmIHdoaWxlIGxlYXJuaW5nIHRvIGNvZGUgaW4gVGFveXVhbiBpU3BhbiBFRUlUMjM=
#jwt expire_time(in seconds)
jwt.expire_time=1800