server {
    listen 80;
    #萬用字元 _，不管來源 Host 是什麼，都吃這個設定
    #因為我這個nginx只服務一個vue網站，並沒有透過名稱去監控
    server_name _;

    root /usr/share/nginx/html;
    #首頁就只要index.html，因為vue只有一個html，其畫面靠router渲染
    index index.html;
    client_max_body_size 10M;

    # Vue Router 用的是 createWebHistory（HTML5 history 模式），
    #端只有一個html，畫面是交由router渲染所以不會指定前後台各自是哪個首頁，因為index.html就是所有頁面了
    location / {
        try_files $uri $uri/ /index.html;
    }

    # location /admin { # 之後可能可以做限定網域
    #     allow 123.456.789.0;
    #     deny all;

    #     try_files $uri $uri/ /index.html;
    # }

    # 對應 vite.config.js 開發時的 /api proxy 設定
    # 要依照依實際docker compose 檔的服務名稱 / port 調整
    location /api/ {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
